/* Patrimonio V2 — application core */
const KEY='patrimonio_v4';
const PRIVATE_KEY='patrimonio_private_mode';
const initial={accounts:{remunerada:64480,efectivo:27000},crypto:{eth:1.1,ethPrice:0},weekly:300,target:1000000,returnRate:7,assets:[],decisions:[],contributions:[],radar:[],alerts:[],market:{lastSync:null,source:null}};
let data=loadData();
let I=null;
let current='dashboard';
let privateMode=localStorage.getItem(PRIVATE_KEY)==='1';
const basePositions=()=>window.V4Portfolio?.positions||[];
const aliases={Meta:'Meta Platforms',Palantir:'Palantir Technologies','S&P 500 ETF':'Vanguard S&P 500 Dist ETF','MSCI World Acc':'iShares Core MSCI World Acc'};
const rawMoney=n=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(n)||0);
const money=n=>privateMode?'••••••':rawMoney(n);
const num=n=>privateMode?'••••••':new Intl.NumberFormat('es-ES',{maximumFractionDigits:4}).format(Number(n)||0);
const pct=n=>privateMode?'••••••':((Number(n)||0)*100).toFixed(1)+'%';
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function loadData(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return {...structuredClone(initial),...(x||{}),accounts:{...initial.accounts,...(x?.accounts||{})},crypto:{...initial.crypto,...(x?.crypto||{})},assets:x?.assets||[],decisions:x?.decisions||[],contributions:x?.contributions||[],radar:x?.radar||[],alerts:x?.alerts||[],market:x?.market||{}}}catch{return structuredClone(initial)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function applyPrivate(){document.body.classList.toggle('private-mode',privateMode);const b=document.getElementById('privacyBtn');if(b)b.textContent=privateMode?'🙈 Mostrar cifras':'👁️ Modo privado'}
function togglePrivate(){privateMode=!privateMode;localStorage.setItem(PRIVATE_KEY,privateMode?'1':'0');applyPrivate();render(current)}
function liq(){return Number(data.accounts.remunerada||0)+Number(data.accounts.efectivo||0)}
function positions(){const overrides=JSON.parse(localStorage.getItem('patrimonio_positions_overrides')||'{}');return basePositions().map(p=>({...p,...(overrides[p.name]||{})}))}
function getPos(name){return positions().find(p=>p.name.toLowerCase()===name.toLowerCase())||positions().find(p=>p.name.toLowerCase()===(aliases[name]||'').toLowerCase())||null}
function total(){return I?.total??liq()+Number(data.crypto.eth||0)*Number(data.crypto.ethPrice||0)}
function rows(){return I?.rows||[]}
function investedCost(){return rows().reduce((s,r)=>s+(Number.isFinite(r.costEUR)?r.costEUR:0),0)}
function portfolioGain(){const value=rows().reduce((s,r)=>s+r.valueEUR,0)+Number(I?.eth?.valueEUR||0);return {cost:investedCost(),value,gain:value-investedCost(),pct:investedCost()?value/investedCost()-1:0}}
function allocation(){const t=total();const all=[...rows().map(r=>[r.name,r.valueEUR]),['Liquidez',liq()],['Ethereum',I?.eth?.valueEUR||0]].filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]);return all.map(x=>`<div class="row"><span><b>${esc(x[0])}</b><br><span class="muted">${money(x[1])}</span></span><span style="min-width:150px"><div class="bar"><div style="width:${Math.min(100,x[1]/Math.max(1,t)*100)}%"></div></div><span class="small">${pct(x[1]/Math.max(1,t))}</span></span></div>`).join('')}
async function sync(){try{const m=await window.MarketV4.sync(),q=m.quotes||{},fx={USD:m.usdEur,HKD:m.hkdEur,JPY:m.jpyEur,GBP:m.gbpEur,EUR:1};const ps=positions();const rs=ps.map(p=>{const qd=q[p.name]||q[aliases[p.name]];const rate=fx[qd?.currency||p.currency]||1;const price=Number(qd?.price);const costRate=fx[p.costCurrency||p.currency]||1;const costEUR=Number(p.quantity)*Number(p.averageCost)*costRate;const valueEUR=Number.isFinite(price)?Number(p.quantity)*price*rate:0;const gainEUR=valueEUR-costEUR;return{name:p.name,quantity:Number(p.quantity),averageCost:Number(p.averageCost),currency:qd?.currency||p.currency,quote:Number.isFinite(price)?price:null,valueEUR,costEUR,gainEUR,returnPct:costEUR?gainEUR/costEUR:0,status:Number.isFinite(price)?'live-price':'pending'}});const inv=rs.reduce((s,r)=>s+r.valueEUR,0);const ethPrice=Number(m.ethPrice)||Number(data.crypto.ethPrice)||0;const ethValue=Number(data.crypto.eth||0)*ethPrice;I={rows:rs,liveInvestment:inv,total:inv+liq()+ethValue,eth:{price:ethPrice,valueEUR:ethValue}};data.crypto.ethPrice=ethPrice;data.market.lastSync=m.updatedAt?new Date(m.updatedAt).toLocaleString('es-ES'):new Date().toLocaleString('es-ES');data.market.source=m.provider||'market-data';save();render(current)}catch(e){console.error(e);render(current)}}
function refreshPrices(){const b=document.getElementById('refreshPricesBtn');if(b){b.disabled=true;b.textContent='⏳ Actualizando...'}sync().finally(()=>{if(b){b.disabled=false;b.textContent='🔄 Actualizar precios'}})}
function setPage(p){current=p;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.p===p));if(pages[p])pages[p]();window.scrollTo(0,0);applyPrivate()}
function render(p=current){if(pages[p])pages[p]();applyPrivate()}
function logDecision(text,type='Sistema'){data.decisions.unshift({date:new Date().toISOString(),text,type});data.decisions=data.decisions.slice(0,100);save()}
function recommendation(){const rs=rows().filter(r=>r.valueEUR>0);if(!rs.length)return {label:'ESPERAR',text:'Sin datos de mercado suficientes.'};const core=rs.find(r=>r.name==='MSCI World Acc');const weights=rs.map(r=>({...r,w:r.valueEUR/Math.max(1,total())}));const under=weights.filter(r=>r.name!=='MSCI World Acc'&&r.w<0.05).sort((a,b)=>a.returnPct-b.returnPct)[0];if(core&&core.returnPct<=-0.10)return {label:'REFORZAR',text:'El MSCI World está en corrección relevante y sigue siendo el núcleo.'};if(under&&under.returnPct<0)return {label:'ANALIZAR',text:`Revisar ${under.name}: peso bajo y rentabilidad negativa.`};return {label:'MANTENER',text:'No hay una señal suficientemente fuerte para concentrar el próximo euro.'}}
function addContribution(){const sel=document.getElementById('contrib-asset'),amt=Number(document.getElementById('contrib-amount').value),price=Number(document.getElementById('contrib-price').value);if(!sel||!(amt>0)||!(price>0))return;const name=sel.value;const p=getPos(name);if(!p)return;const rate=price;const oldQty=Number(p.quantity),oldAvg=Number(p.averageCost);const newQty=amt/rate;const newAvg=((oldQty*oldAvg)+(newQty*price))/(oldQty+newQty);const overrides=JSON.parse(localStorage.getItem('patrimonio_positions_overrides')||'{}');overrides[p.name]={quantity:oldQty+newQty,averageCost:newAvg};localStorage.setItem('patrimonio_positions_overrides',JSON.stringify(overrides));data.contributions.unshift({date:new Date().toISOString(),asset:name,amount:amt,price,newQuantity:newQty,newAverageCost:newAvg});save();logDecision(`Aportación de ${rawMoney(amt)} en ${name}; nuevo precio medio ${newAvg.toFixed(4)}.`,'Aportación');sync()}
function saveConfig(){data.accounts.remunerada=Number(document.getElementById('cfg-rem').value)||0;data.accounts.efectivo=Number(document.getElementById('cfg-cash').value)||0;data.weekly=Number(document.getElementById('cfg-weekly').value)||0;data.target=Number(document.getElementById('cfg-target').value)||0;data.crypto.eth=Number(document.getElementById('cfg-eth').value)||0;const ov=JSON.parse(localStorage.getItem('patrimonio_positions_overrides')||'{}');positions().forEach(p=>{const q=document.getElementById('qty-'+CSS.escape(p.name));const a=document.getElementById('avg-'+CSS.escape(p.name));if(q&&a)ov[p.name]={quantity:Number(q.value)||0,averageCost:Number(a.value)||0}});localStorage.setItem('patrimonio_positions_overrides',JSON.stringify(ov));save();sync()}
const navs=[['dashboard','🏠 Inicio'],['cartera','📊 Cartera'],['liquidez','💶 Liquidez'],['crypto','Ξ Crypto'],['objetivo','🎯 Objetivo'],['riesgo','⚖️ Riesgo'],['decision','🧠 Próximo euro'],['aportaciones','💰 Aportaciones'],['alertas','🚨 Alertas'],['radar','🔎 Radar'],['historial','📝 Historial'],['config','⚙️ Config']];
document.getElementById('nav').innerHTML=navs.map(x=>`<button data-p="${x[0]}" onclick="setPage('${x[0]}')">${x[1]}</button>`).join('');
const pages={
dashboard(){const t=total(),g=portfolioGain(),gap=Math.max(0,data.target-t),rec=recommendation();document.getElementById('app').innerHTML=`<div class="card hero"><span class="badge">MOTOR PATRIMONIAL</span><h2>Patrimonio total</h2><div class="kpi sensitive">${money(t)}</div><p class="muted">${pct(t/data.target)} del objetivo de ${money(data.target)}</p><div class="progress"><div style="width:${Math.min(100,t/data.target*100)}%"></div></div><p class="small">Faltan ${money(gap)}</p></div><div class="grid section"><div class="card">Inversiones<div class="kpi sensitive">${money(I?.liveInvestment||0)}</div></div><div class="card">Liquidez<div class="kpi sensitive">${money(liq())}</div><span>${pct(liq()/Math.max(1,t))}</span></div><div class="card">Ethereum<div class="kpi sensitive">${money(I?.eth?.valueEUR||0)}</div><span>${num(data.crypto.eth)} ETH</span></div><div class="card">P/L total<div class="kpi ${g.gain>=0?'positive':'negative'} sensitive">${money(g.gain)}</div><span>${pct(g.pct)}</span></div></div><div class="two"><div class="card"><h3>Asignación patrimonial</h3>${allocation()}</div><div class="card"><h3>¿Dónde pongo el próximo euro?</h3><span class="badge ${rec.label==='REFORZAR'?'green':rec.label==='ESPERAR'?'amber':''}">${rec.label}</span><p>${esc(rec.text)}</p></div></div>`},
cartera(){const rs=rows();document.getElementById('app').innerHTML=`<h2>Cartera completa</h2><div class="card scroll"><table><thead><tr><th>Activo</th><th>Cantidad</th><th>Precio medio</th><th>Actual</th><th class="right">Valor €</th><th class="right">P/L</th><th>Estado</th></tr></thead><tbody>${rs.map(r=>`<tr><td><b>${esc(r.name)}</b></td><td>${num(r.quantity)}</td><td>${num(r.averageCost)} ${r.currency}</td><td>${r.quote==null?'—':num(r.quote)+' '+r.currency}</td><td class="right"><b>${money(r.valueEUR)}</b></td><td class="right ${r.gainEUR>=0?'positive':'negative'}">${money(r.gainEUR)}<br>${pct(r.returnPct)}</td><td><span class="badge green">LIVE</span></td></tr>`).join('')}</tbody></table></div><div class="card section"><b>Resultado total de inversiones:</b> ${money(portfolioGain().gain)} (${pct(portfolioGain().pct)})<br><span class="muted">El P/L se calcula sobre el coste total de todas las posiciones sincronizadas.</span></div>`},
liquidez(){document.getElementById('app').innerHTML=`<h2>Liquidez</h2><div class="grid"><div class="card">Remunerada<div class="kpi sensitive">${money(data.accounts.remunerada)}</div></div><div class="card">Efectivo<div class="kpi sensitive">${money(data.accounts.efectivo)}</div></div><div class="card">Total<div class="kpi sensitive">${money(liq())}</div></div></div>`},
crypto(){const p=I?.eth?.price||data.crypto.ethPrice||0,v=I?.eth?.valueEUR||Number(data.crypto.eth)*p;document.getElementById('app').innerHTML=`<h2>Ethereum</h2><div class="grid"><div class="card">Cantidad<div class="kpi sensitive">${num(data.crypto.eth)} ETH</div></div><div class="card">Precio EUR<div class="kpi sensitive">${money(p)}</div></div><div class="card">Importe<div class="kpi sensitive">${money(v)}</div></div><div class="card">Peso<div class="kpi sensitive">${pct(v/Math.max(1,total()))}</div></div></div>`},
objetivo(){const t=total(),years=Math.max(1,Math.log(Math.max(1,data.target/t))/Math.log(1+data.returnRate/100));document.getElementById('app').innerHTML=`<h2>Objetivo máximo · 1 M€</h2><div class="card hero"><div class="kpi sensitive">${pct(t/data.target)}</div><p>Patrimonio ${money(t)} · objetivo ${money(data.target)}</p><p>Con un supuesto del ${data.returnRate}% anual, sin nuevas aportaciones, la distancia matemática es de ~${years.toFixed(1)} años.</p><label>Rentabilidad estimada anual (%)<input id="return-rate" type="number" value="${data.returnRate}" onchange="data.returnRate=Number(this.value)||0;save();render('objetivo')"></label></div>`},
riesgo(){const t=total(),rs=rows().slice().sort((a,b)=>b.valueEUR-a.valueEUR),top=rs[0],cw=t?Number(I?.eth?.valueEUR||0)/t:0,tw=t&&top?top.valueEUR/t:0;const level=tw>.25||cw>.15?'ALTO':tw>.15||cw>.10?'MEDIO':'CONTROLADO';const cls=level==='ALTO'?'red':level==='MEDIO'?'amber':'green';document.getElementById('app').innerHTML=`<h2>⚖️ Riesgo</h2><div class="grid"><div class="card">Nivel<div class="score"><span class="badge ${cls}">${level}</span></div></div><div class="card">Mayor posición<div class="kpi">${esc(top?.name||'—')}</div><span>${pct(tw)}</span></div><div class="card">Crypto<div class="kpi">${pct(cw)}</div></div></div><div class="card section"><h3>Concentración</h3>${rs.slice(0,10).map(r=>`<div class="row"><b>${esc(r.name)}</b><span>${money(r.valueEUR)} · ${pct(t?r.valueEUR/t:0)}</span></div>`).join('')}</div>`},
decision(){const r=recommendation();document.getElementById('app').innerHTML=`<h2>🧠 ¿Dónde pongo el próximo euro?</h2><div class="card hero"><span class="badge">DECISIÓN AUTOMÁTICA</span><div class="kpi">${r.label}</div><p>${esc(r.text)}</p><button class="action" onclick="logDecision('${esc(r.label)}: ${esc(r.text)}','Decisión');render('historial')">Guardar decisión</button></div><div class="card section"><h3>Criterios</h3><div class="pill"><span>peso actual</span><span>P/L</span><span>MSCI World como núcleo</span><span>concentración</span></div></div>`},
aportaciones(){const opts=positions().map(p=>`<option>${esc(p.name)}</option>`).join('');document.getElementById('app').innerHTML=`<h2>💰 Aportaciones</h2><div class="card"><div class="form"><label>Activo<select id="contrib-asset">${opts}</select></label><label>Importe (€)<input id="contrib-amount" type="number" min="0" step="0.01"></label><label>Precio de compra por unidad<input id="contrib-price" type="number" min="0" step="0.0001"></label></div><button class="action" style="margin-top:12px" onclick="addContribution()">Registrar aportación y recalcular precio medio</button></div><div class="card section"><h3>Historial</h3>${data.contributions.slice(0,20).map(x=>`<div class="row"><span>${esc(x.asset)}<br><span class="muted">${new Date(x.date).toLocaleString('es-ES')}</span></span><span>${money(x.amount)} · PM ${num(x.newAverageCost)}</span></div>`).join('')||'<div class="empty">Sin aportaciones registradas.</div>'}</div>`},
alertas(){const rs=rows();const alerts=[];const msci=rs.find(r=>r.name==='MSCI World Acc');if(msci&&msci.returnPct<=-.20)alerts.push('MSCI World: caída ≥20% desde el coste. Revisar oportunidad.');rs.filter(r=>r.returnPct<=-.15).forEach(r=>alerts.push(`${r.name}: pérdida ≥15% respecto al coste.`));document.getElementById('app').innerHTML=`<h2>🚨 Alertas</h2><div class="card">${alerts.length?alerts.map(a=>`<div class="row"><span class="badge red">ALERTA</span><span>${esc(a)}</span></div>`):'<div class="empty">No hay alertas activas con las reglas actuales.</div>'}</div>`},
radar(){const rs=rows().map(r=>{const w=r.valueEUR/Math.max(1,total());let score=50;if(r.name==='MSCI World Acc')score+=25;if(w<.03)score+=10;if(w>.20)score-=25;if(r.returnPct<0)score+=10;return {...r,score:Math.max(0,Math.min(100,score))}}).sort((a,b)=>b.score-a.score);document.getElementById('app').innerHTML=`<h2>🔎 Radar de oportunidades</h2><div class="card">${rs.slice(0,10).map(r=>`<div class="row"><span><b>${esc(r.name)}</b><br><span class="muted">Peso ${pct(r.valueEUR/Math.max(1,total()))}</span></span><span class="score">${r.score}/100</span></div>`).join('')}</div>`},
historial(){document.getElementById('app').innerHTML=`<h2>📝 Historial</h2><div class="card">${data.decisions.slice(0,50).map(d=>`<div class="row"><span>${esc(d.text)}<br><span class="muted">${esc(d.type)} · ${new Date(d.date).toLocaleString('es-ES')}</span></span></div>`).join('')||'<div class="empty">Todavía no hay decisiones.</div>'}</div>`},
config(){const ps=positions();document.getElementById('app').innerHTML=`<h2>⚙️ Configuración</h2><div class="card"><h3>Patrimonio</h3><div class="form"><label>Cuenta remunerada (€)<input id="cfg-rem" type="number" value="${data.accounts.remunerada}"></label><label>Efectivo (€)<input id="cfg-cash" type="number" value="${data.accounts.efectivo}"></label><label>Aportación semanal (€)<input id="cfg-weekly" type="number" value="${data.weekly}"></label><label>Objetivo (€)<input id="cfg-target" type="number" value="${data.target}"></label><label>Ethereum (ETH)<input id="cfg-eth" type="number" step="0.0001" value="${data.crypto.eth}"></label></div></div><h3>Posiciones</h3><div class="grid">${ps.map(p=>`<div class="card"><b>${esc(p.name)}</b><label>Cantidad<input id="qty-${esc(p.name)}" type="number" step="0.0001" value="${p.quantity}"></label><label>Precio medio<input id="avg-${esc(p.name)}" type="number" step="0.0001" value="${p.averageCost}"></label></div>`).join('')}</div><button class="action" onclick="saveConfig()">💾 Guardar todo y actualizar</button><div class="card section"><h3>Seguridad</h3><button class="action secondary" onclick="togglePrivate()">${privateMode?'🙈 Mostrar cifras':'👁️ Activar modo privado'}</button><p class="muted">El acceso está protegido por la capa de autenticación de la PWA.</p></div>`}
};
window.pages=pages;window.data=data;window.save=save;window.total=total;window.liq=liq;window.money=money;window.num=num;window.pct=pct;window.esc=esc;window.current=current;window.setPage=setPage;window.render=render;window.togglePrivate=togglePrivate;window.refreshPrices=refreshPrices;window.sync=sync;window.savePatrimonioConfig=saveConfig;window.addContribution=addContribution;
render('dashboard');setTimeout(sync,100);
