/* Patrimonio V2 — capa final de pulido y coherencia */
(function(){
  const KEY='patrimonio_v4', OKEY='patrimonio_positions_overrides', SKEY='patrimonio_security_settings', EKEY='patrimonio_crypto_cost_eur';
  const aliases={Meta:'Meta Platforms',Palantir:'Palantir Technologies','S&P 500 ETF':'Vanguard S&P 500 Dist ETF','MSCI World Acc':'iShares Core MSCI World Acc'};
  const fx=m=>({USD:Number(m.usdEur)||0.85,HKD:Number(m.hkdEur)||0.108,JPY:Number(m.jpyEur)||0.0058,GBP:Number(m.gbpEur)||0.856,EUR:1});
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
  const save=d=>localStorage.setItem(KEY,JSON.stringify(d));
  const overrides=()=>{try{return JSON.parse(localStorage.getItem(OKEY)||'{}')}catch{return {}}};
  const fmt=n=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(n)||0);
  const num=n=>new Intl.NumberFormat('es-ES',{maximumFractionDigits:4}).format(Number(n)||0);
  const pct=n=>((Number(n)||0)*100).toFixed(1)+'%';
  const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  function data(){const d=read();return {accounts:{remunerada:Number(d.accounts?.remunerada??64480),efectivo:Number(d.accounts?.efectivo??27000)},crypto:{eth:Number(d.crypto?.eth??1.1)},weekly:Number(d.weekly??300),target:Number(d.target??1000000),returnRate:Number(d.returnRate??7),decisions:d.decisions||[],contributions:d.contributions||[],radar:d.radar||[],alerts:d.alerts||[]}}
  async function snapshot(){const m=await window.MarketV4.sync(), f=fx(m), ov=overrides(), ps=(window.V4Portfolio?.positions||[]).map(p=>({...p,...(ov[p.name]||{})}));const rows=ps.map(p=>{const q=m.quotes?.[p.name]||m.quotes?.[aliases[p.name]], price=Number(q?.price), value=Number.isFinite(price)?Number(p.quantity)*price*(f[q?.currency||p.currency]||1):0, cost=Number(p.quantity)*Number(p.averageCost)*(f[p.costCurrency||p.currency]||1);return {...p,quote:Number.isFinite(price)?price:null,quoteCurrency:q?.currency||p.currency,valueEUR:value,costEUR:cost,gainEUR:value-cost,returnPct:cost?(value-cost)/cost:0}});const d=data(),ethPrice=Number(m.ethPrice)||0,ethValue=d.crypto.eth*ethPrice;let ethCost=Number(d.crypto.ethCostEUR);if(!Number.isFinite(ethCost))ethCost=Number(localStorage.getItem(EKEY)||0)||0;const invCost=rows.reduce((s,r)=>s+r.costEUR,0),invValue=rows.reduce((s,r)=>s+r.valueEUR,0),totalCost=invCost+ethCost,totalValue=invValue+ethValue;return {m,d,rows,eth:{qty:d.crypto.eth,price:ethPrice,valueEUR:ethValue,costEUR:ethCost,gainEUR:ethValue-ethCost},invCost,invValue,totalCost,totalValue,totalGain:totalValue-totalCost,totalPct:totalCost?(totalValue-totalCost)/totalCost:0,patrimony:totalValue+d.accounts.remunerada+d.accounts.efectivo};}
  function chart(s){const max=Math.max(s.totalCost,s.totalValue,1),a=s.totalCost/max*100,b=s.totalValue/max*100,d=s.totalGain;return `<div class="card section"><h3>📈 Capital invertido vs valor actual</h3><div class="small">Capital invertido <b>${fmt(s.totalCost)}</b></div><div class="progress"><div style="width:${a}%"></div></div><div class="small" style="margin-top:12px">Valor actual <b>${fmt(s.totalValue)}</b></div><div class="progress"><div style="width:${b}%"></div></div><div class="grid" style="margin-top:14px"><div><span class="muted">Diferencia</span><div class="kpi ${d>=0?'positive':'negative'}">${fmt(d)}</div></div><div><span class="muted">Rentabilidad</span><div class="kpi ${d>=0?'positive':'negative'}">${pct(s.totalPct)}</div></div></div><div class="small muted">Acciones + ETFs + Ethereum. Liquidez excluida.</div></div>`}
  function renderDashboard(s){const r=s.rows.slice().sort((a,b)=>b.valueEUR-a.valueEUR),liq=s.d.accounts.remunerada+s.d.accounts.efectivo,rec=recommend(s),gap=Math.max(0,s.d.target-s.patrimony);document.getElementById('app').innerHTML=`<div class="card hero"><span class="badge">MOTOR PATRIMONIAL</span><h2>Patrimonio total</h2><div class="kpi sensitive">${fmt(s.patrimony)}</div><p class="muted">${pct(s.patrimony/s.d.target)} del objetivo de ${fmt(s.d.target)}</p><div class="progress"><div style="width:${Math.min(100,s.patrimony/s.d.target*100)}%"></div></div><p class="small">Faltan ${fmt(gap)}</p></div><div class="grid section"><div class="card">Inversiones<div class="kpi sensitive">${fmt(s.invValue)}</div><span>P/L ${fmt(s.rows.reduce((x,r)=>x+r.gainEUR,0))}</span></div><div class="card">Liquidez<div class="kpi sensitive">${fmt(liq)}</div><span>${pct(liq/Math.max(1,s.patrimony))}</span></div><div class="card">Ethereum<div class="kpi sensitive">${fmt(s.eth.valueEUR)}</div><span>${num(s.eth.qty)} ETH · P/L ${s.eth.costEUR?fmt(s.eth.gainEUR):'coste pendiente'}</span></div><div class="card">P/L total<div class="kpi ${s.totalGain>=0?'positive':'negative'} sensitive">${fmt(s.totalGain)}</div><span>${s.eth.costEUR?pct(s.totalPct):'configura coste ETH'}</span></div></div>${chart(s)}<div class="two"><div class="card"><h3>Asignación</h3>${r.concat([ {name:'Liquidez',valueEUR:liq},{name:'Ethereum',valueEUR:s.eth.valueEUR}]).filter(x=>x.valueEUR>0).map(x=>`<div class="row"><b>${esc(x.name)}</b><span>${fmt(x.valueEUR)} · ${pct(x.valueEUR/s.patrimony)}</span></div>`).join('')}</div><div class="card"><h3>¿Dónde pongo el próximo euro?</h3><span class="badge ${rec.label==='REFORZAR'?'green':rec.label==='ESPERAR'?'amber':''}">${rec.label}</span><p>${esc(rec.text)}</p></div></div>`;window.applyPrivate?.()}
  function recommend(s){const core=s.rows.find(r=>r.name==='MSCI World Acc'), under=s.rows.filter(r=>r.name!=='MSCI World Acc'&&r.valueEUR>0&&r.valueEUR/s.patrimony<.05).sort((a,b)=>a.returnPct-b.returnPct)[0];if(core&&core.returnPct<=-.10)return {label:'REFORZAR',text:'MSCI World está en corrección relevante y sigue siendo el núcleo.'};if(under&&under.returnPct<0)return {label:'ANALIZAR',text:`Revisar ${under.name}: peso bajo y rentabilidad negativa.`};return {label:'MANTENER',text:'No hay una señal suficientemente fuerte para concentrar el próximo euro.'}}
  function renderCartera(s){document.getElementById('app').innerHTML=`<h2>📊 Cartera completa</h2><div class="card scroll"><table><thead><tr><th>Activo</th><th>Cantidad</th><th>Precio medio</th><th>Actual</th><th class="right">Valor €</th><th class="right">P/L</th><th>Estado</th></tr></thead><tbody>${s.rows.map(r=>`<tr><td><b>${esc(r.name)}</b></td><td>${num(r.quantity)}</td><td>${num(r.averageCost)} ${r.costCurrency}</td><td>${r.quote==null?'—':num(r.quote)+' '+r.quoteCurrency}</td><td class="right"><b>${fmt(r.valueEUR)}</b></td><td class="right ${r.gainEUR>=0?'positive':'negative'}">${fmt(r.gainEUR)}<br>${pct(r.returnPct)}</td><td><span class="badge ${r.quote==null?'amber':'green'}">${r.quote==null?'PENDIENTE':'LIVE'}</span></td></tr>`).join('')}<tr><td><b>Ethereum</b></td><td>${num(s.eth.qty)}</td><td>${s.eth.costEUR?fmt(s.eth.costEUR/s.eth.qty):'—'}</td><td>${fmt(s.eth.price)}</td><td class="right"><b>${fmt(s.eth.valueEUR)}</b></td><td class="right ${s.eth.gainEUR>=0?'positive':'negative'}">${s.eth.costEUR?fmt(s.eth.gainEUR):'—'}<br>${s.eth.costEUR?pct(s.eth.gainEUR/s.eth.costEUR):'coste pendiente'}</td><td><span class="badge green">LIVE</span></td></tr></tbody></table></div>${chart(s)}`}
  function renderLiquidity(s){const l=s.d.accounts.remunerada+s.d.accounts.efectivo;document.getElementById('app').innerHTML=`<h2>💶 Liquidez</h2><div class="grid"><div class="card">Cuenta remunerada<div class="kpi sensitive">${fmt(s.d.accounts.remunerada)}</div></div><div class="card">Efectivo<div class="kpi sensitive">${fmt(s.d.accounts.efectivo)}</div></div><div class="card">Total liquidez<div class="kpi sensitive">${fmt(l)}</div><span>${pct(l/s.patrimony)}</span></div></div><div class="card section"><p class="muted">La liquidez no entra en el P/L de mercado, pero sí en el patrimonio total.</p></div>`}
  function renderCrypto(s){document.getElementById('app').innerHTML=`<h2>Ξ Crypto</h2><div class="grid"><div class="card">Ethereum<div class="kpi sensitive">${num(s.eth.qty)} ETH</div></div><div class="card">Precio actual<div class="kpi sensitive">${fmt(s.eth.price)}</div></div><div class="card">Valor<div class="kpi sensitive">${fmt(s.eth.valueEUR)}</div></div><div class="card">P/L<div class="kpi ${s.eth.gainEUR>=0?'positive':'negative'} sensitive">${s.eth.costEUR?fmt(s.eth.gainEUR):'Configurar coste'}</div></div></div><div class="card section"><p>Para calcular correctamente el P/L de ETH necesitamos el <b>coste total de adquisición</b>. Puedes introducirlo en ⚙️ Config.</p></div>`}
  function renderObjective(s){const years=s.patrimony>0&&s.d.returnRate>0?Math.log(s.d.target/s.patrimony)/Math.log(1+s.d.returnRate/100):0;document.getElementById('app').innerHTML=`<h2>🎯 Objetivo</h2><div class="card hero"><div class="kpi sensitive">${pct(s.patrimony/s.d.target)}</div><p>Patrimonio ${fmt(s.patrimony)} · objetivo ${fmt(s.d.target)}</p><p>Al ${s.d.returnRate}% anual, sin nuevas aportaciones: ${years>0?years.toFixed(1)+' años':'—'}.</p></div><div class="card section"><h3>Variables</h3><label>Rentabilidad anual estimada (%)<input id="cfg-return" type="number" step="0.1" value="${s.d.returnRate}"></label><button class="action" style="margin-top:10px" onclick="window.finalSaveReturn()">Guardar</button></div>`}
  function renderRisk(s){const sorted=s.rows.slice().sort((a,b)=>b.valueEUR-a.valueEUR),top=sorted[0],topW=top?s.patrimony?top.valueEUR/s.patrimony:0:0,cw=s.patrimony?s.eth.valueEUR/s.patrimony:0,level=topW>.25||cw>.15?'ALTO':topW>.15||cw>.10?'MEDIO':'CONTROLADO',cls=level==='ALTO'?'red':level==='MEDIO'?'amber':'green';document.getElementById('app').innerHTML=`<h2>⚖️ Riesgo</h2><div class="grid"><div class="card">Nivel<div class="score"><span class="badge ${cls}">${level}</span></div></div><div class="card">Mayor posición<div class="kpi">${esc(top?.name||'—')}</div><span>${pct(topW)}</span></div><div class="card">Ethereum<div class="kpi">${pct(cw)}</div></div></div><div class="card section"><h3>Concentración</h3>${sorted.map(r=>`<div class="row"><b>${esc(r.name)}</b><span>${fmt(r.valueEUR)} · ${pct(s.patrimony?r.valueEUR/s.patrimony:0)}</span></div>`).join('')}</div>`}
  function renderDecision(s){const r=recommend(s);document.getElementById('app').innerHTML=`<h2>🧠 ¿Dónde pongo el próximo euro?</h2><div class="card hero"><span class="badge">DECISIÓN AUTOMÁTICA</span><div class="kpi">${r.label}</div><p>${esc(r.text)}</p><button class="action" onclick="window.finalLog('${esc(r.label)}: ${esc(r.text)}')">Guardar decisión</button></div><div class="card section"><h3>Base de decisión</h3><div class="pill"><span>Peso</span><span>P/L</span><span>MSCI World núcleo</span><span>Corrección</span></div></div>`}
  function renderContrib(s){const opts=s.rows.map(r=>`<option value="${esc(r.name)}">${esc(r.name)}</option>`).join('');document.getElementById('app').innerHTML=`<h2>💰 Aportaciones</h2><div class="card"><div class="form"><label>Activo<select id="fc-asset">${opts}</select></label><label>Importe (€)<input id="fc-amt" type="number" step="1"></label><label>Precio de compra<input id="fc-price" type="number" step="0.0001"></label></div><button class="action" style="margin-top:12px" onclick="window.finalContribution()">Registrar aportación</button></div><div class="card section"><b>Aportación semanal:</b> ${fmt(s.d.weekly)}</div>`}
  function renderAlerts(s){document.getElementById('app').innerHTML=`<h2>🚨 Alertas</h2><div class="card"><h3>Alertas configuradas</h3>${s.d.alerts.length?s.d.alerts.map(a=>`<div class="row"><span>${esc(a.text||a.name||JSON.stringify(a))}</span></div>`).join(''):'<div class="empty">No hay alertas guardadas.</div>'}</div><div class="card section"><h3>Regla MSCI World</h3><p>La alerta de corrección del 20% puede configurarse cuando tengamos histórico de máximo fiable.</p></div>`}
  function renderRadar(s){document.getElementById('app').innerHTML=`<h2>🔎 Radar</h2><div class="card">${s.d.radar.length?s.d.radar.map(r=>`<div class="row"><b>${esc(r.name||r.asset||'Oportunidad')}</b><span>${esc(r.text||r.reason||'Sin detalle')}</span></div>`).join(''):'<div class="empty">El radar todavía no tiene oportunidades registradas.</div>'}</div>`}
  function renderHistory(s){document.getElementById('app').innerHTML=`<h2>📝 Historial</h2><div class="card">${s.d.decisions.length?s.d.decisions.slice(0,50).map(x=>`<div class="row"><span><b>${esc(x.type||'Sistema')}</b><br>${esc(x.text)}</span><span class="small muted">${new Date(x.date).toLocaleString('es-ES')}</span></div>`).join(''):'<div class="empty">Todavía no hay decisiones registradas.</div>'}</div>`}
  function renderConfig(s){const ov=overrides();document.getElementById('app').innerHTML=`<h2>⚙️ Configuración</h2><div class="card"><h3>Patrimonio y liquidez</h3><div class="form"><label>Remunerada (€)<input id="fc-rem" type="number" value="${s.d.accounts.remunerada}"></label><label>Efectivo (€)<input id="fc-cash" type="number" value="${s.d.accounts.efectivo}"></label><label>Aportación semanal (€)<input id="fc-weekly" type="number" value="${s.d.weekly}"></label><label>Objetivo (€)<input id="fc-target" type="number" value="${s.d.target}"></label><label>ETH (cantidad)<input id="fc-eth" type="number" step="0.0001" value="${s.eth.qty}"></label><label>Coste total ETH (€)<input id="fc-ethcost" type="number" step="0.01" value="${s.eth.costEUR||''}" placeholder="Introduce tu coste real"></label><label>Rentabilidad anual estimada (%)<input id="fc-return" type="number" step="0.1" value="${s.d.returnRate}"></label></div><button class="action" style="margin-top:12px" onclick="window.finalSaveConfig()">Guardar cambios</button></div><div class="card section"><h3>Posiciones</h3>${s.rows.map(r=>`<div class="row"><b>${esc(r.name)}</b><span>${num(r.quantity)} · ${num(r.averageCost)} ${r.costCurrency}</span></div>`).join('')}</div><div class="card section"><h3>🔐 Seguridad</h3><p class="muted">La configuración de Face ID, bloqueo y modo privado está en el módulo Seguridad.</p><button class="action" onclick="window.openSecuritySettings()">Configurar seguridad</button></div>`}
  async function go(p){const s=await snapshot();const f={dashboard:renderDashboard,cartera:renderCartera,liquidez:renderLiquidity,crypto:renderCrypto,objetivo:renderObjective,riesgo:renderRisk,decision:renderDecision,aportaciones:renderContrib,alertas:renderAlerts,radar:renderRadar,historial:renderHistory,config:renderConfig};(f[p]||renderDashboard)(s);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.p===p));window.scrollTo(0,0)}
  window.finalGo=go;
  window.finalLog=function(text){const d=read();d.decisions=d.decisions||[];d.decisions.unshift({date:new Date().toISOString(),text,type:'Decisión'});save(d);go('historial')};
  window.finalSaveReturn=function(){const d=read();d.returnRate=Number(document.getElementById('cfg-return').value)||0;save(d);go('objetivo')};
  window.finalSaveConfig=function(){const d=read();d.accounts={remunerada:Number(document.getElementById('fc-rem').value)||0,efectivo:Number(document.getElementById('fc-cash').value)||0};d.weekly=Number(document.getElementById('fc-weekly').value)||0;d.target=Number(document.getElementById('fc-target').value)||0;d.returnRate=Number(document.getElementById('fc-return').value)||0;d.crypto={...(d.crypto||{}),eth:Number(document.getElementById('fc-eth').value)||0,ethCostEUR:Number(document.getElementById('fc-ethcost').value)||0};localStorage.setItem(EKEY,String(d.crypto.ethCostEUR));save(d);go('config')};
  window.finalContribution=function(){const name=document.getElementById('fc-asset').value,amt=Number(document.getElementById('fc-amt').value),price=Number(document.getElementById('fc-price').value);if(!(amt>0&&price>0))return alert('Introduce importe y precio válidos.');const ov=overrides(),p=(window.V4Portfolio?.positions||[]).find(x=>x.name===name);if(!p)return;const x={...p,...(ov[p.name]||{})},q=amt/price,newAvg=((Number(x.quantity)*Number(x.averageCost))+(q*price))/(Number(x.quantity)+q);ov[p.name]={quantity:Number(x.quantity)+q,averageCost:newAvg};localStorage.setItem(OKEY,JSON.stringify(ov));const d=read();d.contributions=d.contributions||[];d.contributions.unshift({date:new Date().toISOString(),asset:name,amount:amt,price,newQuantity:q,newAverageCost:newAvg});save(d);go('aportaciones')};
  function mount(){const nav=document.getElementById('nav');if(!nav)return;nav.innerHTML=[['dashboard','🏠 Inicio'],['cartera','📊 Cartera'],['liquidez','💶 Liquidez'],['crypto','Ξ Crypto'],['objetivo','🎯 Objetivo'],['riesgo','⚖️ Riesgo'],['decision','🧠 Próximo euro'],['aportaciones','💰 Aportaciones'],['alertas','🚨 Alertas'],['radar','🔎 Radar'],['historial','📝 Historial'],['config','⚙️ Config'],['seguridad','🔐 Seguridad']].map(x=>`<button data-p="${x[0]}">${x[1]}</button>`).join('');nav.querySelectorAll('button').forEach(b=>b.onclick=()=>b.dataset.p==='seguridad'?window.openSecuritySettings():go(b.dataset.p));setTimeout(()=>go('dashboard'),50)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,200));else setTimeout(mount,200);
})();
