/* RADAR UI V4 — mobile-first, portfolio-aware, evidence-first */
(function(){
 function boot(){
  if(typeof pages==='undefined'||typeof rows!=='function'||typeof total!=='function'||typeof esc!=='function'){setTimeout(boot,100);return;}
  pages.radar=async function(){
   const rs=rows().filter(r=>Number(r.valueEUR)>0), t=Math.max(1,total());
   const universe=window.RadarUniverseV1?.candidates||[];
   const prep=window.RadarDataAdapterV1&&window.RadarIntelligenceV5?await window.RadarDataAdapterV1.prepare(universe,rs,t):{candidates:[],ctx:{},macro:null,news:{},coverage:0};
   const ranked=window.RadarIntelligenceV5?window.RadarIntelligenceV5.rank(prep.candidates,prep.ctx,prep.macro,prep.news):[];
   const opp=ranked.filter(x=>x.radar.action==='OPORTUNIDAD'),watch=ranked.filter(x=>x.radar.action==='VIGILAR'),pending=ranked.filter(x=>x.radar.action==='DATOS_INSUFICIENTES');
   const climate=prep.macro?.regime==='INFLACION_PERSISTENTE_RIESGO_GEOPOLITICO'?'PRUDENTE':opp.length>=2?'FAVORABLE':watch.length>=2?'SELECTIVO':'PRUDENTE';
   const first=opp[0]||watch[0]||pending[0];
   document.getElementById('app').innerHTML=`<div class="radar-head"><div><span class="radar-eyebrow">INTELLIGENCE CENTER V4</span><h2>🔎 Radar</h2><p>Busca oportunidades en el mercado y las cruza con <b>tu cartera global</b>.</p></div><div class="climate ${climate==='FAVORABLE'?'good':climate==='SELECTIVO'?'warn':'care'}">${climate}<small>clima</small></div></div><div class="radar-stats"><div><b>${opp.length}</b><span>Validadas</span></div><div><b>${watch.length}</b><span>En vigilancia</span></div><div><b>${pending.length}</b><span>Datos pendientes</span></div></div><div class="radar-card hero-radar"><div><span class="radar-eyebrow">PRÓXIMO EURO</span><h3>${first?esc(first.name):'Sin señal'}</h3><p>${first?labelText(first.radar.action):'No hay suficiente evidencia todavía.'}</p></div><strong>${first?first.radar.score:'—'}<small>/100</small></strong></div><div class="radar-card"><div class="radar-title"><h3>🏆 Ranking para tu cartera</h3><span>${ranked.length} candidatos</span></div>${ranked.slice(0,10).map(card).join('')}</div><div class="radar-card"><div class="radar-title"><h3>🌡️ Clima macro</h3><span>último snapshot</span></div><div class="risk-line"><span>Régimen</span><b>${esc(prep.macro?.regime||'SIN DATOS')}</b></div><div class="risk-line"><span>Inflación USA</span><b>${prep.macro?.inflation!=null?prep.macro.inflation+'%':'—'}</b></div><div class="risk-line"><span>Presión de tipos</span><b>${prep.macro?.ratePressure!=null?prep.macro.ratePressure+'/100':'—'}</b></div><div class="risk-line"><span>Riesgo energético</span><b>${prep.macro?.oilShock!=null?prep.macro.oilShock+'/100':'—'}</b></div><p class="hint">El entorno actual se incorpora como factor de contexto, nunca como sustituto de los fundamentales.</p></div><div class="radar-card"><div class="radar-title"><h3>🛡️ Seguridad de datos</h3><span>anti-falsas señales</span></div><div class="risk-line"><span>Cobertura de precios</span><b>${Math.round((prep.coverage||0)*100)}%</b></div><div class="risk-line"><span>Datos fundamentales</span><b>Validación obligatoria</b></div><div class="risk-line"><span>Confianza mínima</span><b>65/100</b></div><p class="safety">Los candidatos sin datos fundamentales suficientes no se convierten artificialmente en oportunidades.</p></div>`;
  };
  function labelText(a){return a==='OPORTUNIDAD'?'Mejor equilibrio actual entre oportunidad, riesgo y encaje.':a==='VIGILAR'?'Interesante, pero necesita confirmación.':'No hay evidencia suficiente para concentrar capital.'}
  function card(x,i){const r=x.radar||{},cls=r.action==='OPORTUNIDAD'?'good':r.action==='VIGILAR'?'warn':'care';return `<div class="radar-item"><div class="rank">${i+1}</div><div class="radar-main"><b>${esc(x.name)}</b><span>${r.action||'ESPERAR'} · confianza ${r.confidence||0}% · calidad datos ${r.dataQuality||0}%</span></div><div class="radar-score ${cls}">${r.score||0}</div></div>`}
  const s=document.createElement('style');s.textContent=`.radar-head{display:flex;justify-content:space-between;align-items:center;margin:4px 2px 14px}.radar-head h2{margin:3px 0;font-size:28px}.radar-head p{margin:0;color:var(--muted);font-size:13px}.radar-eyebrow{font-size:10px;font-weight:800;letter-spacing:1.5px;color:var(--blue)}.climate{min-width:78px;text-align:center;border-radius:14px;padding:10px 8px;font-weight:800;font-size:11px}.climate small{display:block;font-weight:500;margin-top:3px}.climate.good,.radar-score.good{background:#e9f8ef;color:#167347}.climate.warn,.radar-score.warn{background:#fff7df;color:#8a5a00}.climate.care,.radar-score.care{background:#fdecec;color:#b52c2c}.radar-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:10px}.radar-stats div{background:#fff;border:1px solid var(--border);border-radius:13px;padding:12px}.radar-stats b{font-size:23px;display:block}.radar-stats span{font-size:11px;color:var(--muted)}.radar-card{background:#fff;border:1px solid var(--border);border-radius:17px;padding:15px;margin:10px 0;box-shadow:0 2px 8px #00000008}.hero-radar{background:linear-gradient(135deg,#111827,#253b66);color:#fff;display:flex;justify-content:space-between;align-items:center}.hero-radar .radar-eyebrow{color:#a8c7ff}.hero-radar h3{font-size:21px;margin:5px 0}.hero-radar p{margin:0;color:#cbd5e1;font-size:12px}.hero-radar>strong{font-size:38px}.hero-radar strong small{font-size:11px;color:#cbd5e1}.radar-title{display:flex;justify-content:space-between;align-items:center}.radar-title h3{margin:0 0 8px}.radar-title span{font-size:11px;color:var(--muted)}.radar-item{display:flex;align-items:center;gap:10px;padding:12px 0;border-bottom:1px solid var(--border)}.radar-item:last-child{border-bottom:0}.rank{width:25px;height:25px;border-radius:50%;background:#eef2f7;display:grid;place-items:center;font-size:11px;font-weight:800}.radar-main{flex:1}.radar-main b{display:block;font-size:14px}.radar-main span{display:block;color:var(--muted);font-size:10px;margin-top:3px}.radar-score{width:42px;height:42px;border-radius:11px;display:grid;place-items:center;font-weight:900}.risk-line{display:flex;justify-content:space-between;gap:12px;padding:10px 0;border-bottom:1px solid var(--border);font-size:13px}.hint,.safety{font-size:11px;color:var(--muted);line-height:1.5}.safety{background:#fff7df;padding:11px;border-radius:10px;color:#6b4d00}.chips{display:flex;flex-wrap:wrap;gap:6px}`;document.head.appendChild(s);
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
