/* RADAR V6 — V5 intelligence engine wired to live validated context */
(function(){
 function boot(){
  if(typeof pages==='undefined'||typeof rows!=='function'||typeof total!=='function'||typeof money!=='function'||typeof num!=='function'||typeof esc!=='function'||!window.RadarIntelligenceV5||!window.RadarUniverseV1){setTimeout(boot,100);return;}
  const portfolioMeta=()=>{const m={};(window.V4Portfolio?.positions||[]).forEach(p=>m[p.ticker||p.name]=p);return m};
  async function makeUniverse(){
   const meta=portfolioMeta();
   const held=rows().map(r=>{const p=meta[r.name]||meta[r.ticker]||{};return{...r,ticker:p.ticker||r.ticker||r.name,sector:p.sector,country:p.country,assetType:p.assetType||'stock'}});
   const prepared=window.RadarDataAdapterV1?await RadarDataAdapterV1.prepare(window.RadarUniverseV1.candidates,held,total()):null;
   const snap=prepared?.snapshot?.assets||{};
   return {assets:(prepared?.candidates||window.RadarUniverseV1.candidates).map(a=>({...a,...(snap[a.ticker]||{}),price:a.price??snap[a.ticker]?.price??null,currency:a.currency??snap[a.ticker]?.currency??null,updatedAt:a.updatedAt??snap[a.ticker]?.updatedAt??null,held:!!a.held})),macro:prepared?.macro||null,news:prepared?.news||null,coverage:prepared?.coverage||0,snapshotAgeDays:prepared?.snapshotAgeDays||9999};
  }
  pages.radar=async function(){
   const rs=rows().filter(r=>Number(r.valueEUR)>0),t=Math.max(1,total()),meta=portfolioMeta();
   const ctx=RadarIntelligenceV5.buildContext(rs.map(r=>{const p=meta[r.name]||meta[r.ticker]||{};return{ticker:p.ticker||r.name,name:r.name,valueEUR:r.valueEUR,sector:p.sector,country:p.country}}),t);
   const data=await makeUniverse(),ranked=RadarIntelligenceV5.rank(data.assets,ctx,data.macro,data.news),opp=ranked.filter(x=>x.radar.action==='OPORTUNIDAD'),watch=ranked.filter(x=>x.radar.action==='VIGILAR'),insufficient=ranked.filter(x=>x.radar.action==='DATOS_INSUFICIENTES'),top=opp[0]||watch[0]||insufficient[0],climate=opp.length>=3?'FAVORABLE':watch.length>=3?'SELECTIVO':'PRUDENTE';
   document.getElementById('app').innerHTML=`<div class="radar-head"><div><span class="radar-eyebrow">INTELLIGENCE CENTER · V6</span><h2>🔎 Radar</h2><p>Mercado global cruzado con tu patrimonio y contexto macro.</p></div><div class="climate ${climate==='FAVORABLE'?'good':climate==='SELECTIVO'?'warn':'care'}">${climate}<small>clima</small></div></div><div class="radar-stats"><div><b>${opp.length}</b><span>Oportunidades</span></div><div><b>${watch.length}</b><span>Vigilancia</span></div><div><b>${ranked.length}</b><span>Activos analizados</span></div><div><b>${Math.round(data.coverage*100)}%</b><span>Cobertura de precios</span></div></div><div class="radar-card hero-radar"><div><span class="radar-eyebrow">PRÓXIMO EURO</span><h3>${top?esc(top.name):'Sin señal'}</h3><p>${top?top.radar.action==='DATOS_INSUFICIENTES'?'Datos insuficientes para recomendar.':top.radar.action==='VIGILAR'?'Interesante, pero necesita confirmación.':'Mejor oportunidad validada disponible.':'Sin datos suficientes.'}</p></div><strong>${top?top.radar.score:'—'}<small>/100</small></strong></div>${opp.length?`<div class="radar-card"><div class="radar-title"><h3>🏆 Mejores oportunidades</h3><span>Encaje global</span></div>${opp.slice(0,10).map(card).join('')}</div>`:''}<div class="radar-card"><div class="radar-title"><h3>👀 Vigilancia y datos pendientes</h3><span>${watch.length+insufficient.length}</span></div>${watch.concat(insufficient).slice(0,12).map(card).join('')||'<div class="empty">Sin señales todavía.</div>'}</div><div class="radar-card"><div class="radar-title"><h3>🌍 Contexto que está usando el motor</h3><span>${data.macro?.regime||'Sin macro'}</span></div><div class="risk-line"><span>Inflación</span><b>${data.macro?.inflation??'—'}%</b></div><div class="risk-line"><span>Presión de tipos</span><b>${data.macro?.ratePressure??'—'}/100</b></div><div class="risk-line"><span>Shock petróleo</span><b>${data.macro?.oilShock??'—'}/100</b></div><div class="risk-line"><span>Riesgo recesión</span><b>${data.macro?.recessionRisk??'—'}/100</b></div><p class="hint">Las noticias se ponderan por fiabilidad y antigüedad; el contexto macro modifica el análisis, no lo sustituye.</p></div><div class="radar-card"><div class="radar-title"><h3>🛡️ Control de seguridad</h3><span>Global</span></div><div class="risk-line"><span>Mayor posición</span><b>${rs.length?Math.round(Math.max(...rs.map(r=>r.valueEUR/t))*100):0}%</b></div><div class="risk-line"><span>Liquidez</span><b>${money(typeof liq==='function'?liq():0)}</b></div><div class="risk-line"><span>Datos insuficientes</span><b>${insufficient.length}</b></div><div class="risk-line"><span>Snapshot macro</span><b>${data.snapshotAgeDays<2?'ACTUAL':'ANTIGUO'}</b></div><p class="hint">Una señal no puede convertirse en recomendación si faltan datos críticos o la confianza es baja.</p></div>`;
  };
  function card(x,i){const r=x.radar||{},cls=r.action==='OPORTUNIDAD'?'good':r.action==='VIGILAR'?'warn':'care';return `<div class="radar-item"><div class="rank">${i+1}</div><div class="radar-main"><b>${esc(x.name)}</b><span>${r.action||'ESPERAR'} · confianza ${r.confidence||0}% · datos ${r.dataQuality||0}% · ${x.price!=null?'precio '+num(x.price):'precio pendiente'}</span></div><div class="radar-score ${cls}">${r.score||0}</div></div>`}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
 })();
