/* RADAR ENGINE V3 — scoring robusto, cartera-aware y conservador */
(function(){
  const VERSION='3.0.0';
  const DEFAULT={weights:{quality:.22,valuation:.18,growth:.14,financialStrength:.12,trend:.07,drawdown:.07,diversification:.12,liquidity:.04,risk:.04},thresholds:{opportunity:78,watch:62},maxPosition:.10,maxSector:.25,maxCountry:.45,maxMissingCritical:2};
  const clamp=(x,a=0,b=100)=>Math.max(a,Math.min(b,Number(x)||0));
  const norm=(x,min=0,max=100)=>x===null||x===undefined||!Number.isFinite(Number(x))?null:clamp((Number(x)-min)/(max-min)*100);
  const avg=v=>{v=v.filter(x=>x!==null&&Number.isFinite(Number(x)));return v.length?v.reduce((a,b)=>a+Number(b),0)/v.length:null};
  function riskScore(a){let s=70;if(Number.isFinite(a.beta)){if(a.beta>1.6)s-=25;else if(a.beta>1.3)s-=12;else if(a.beta<.8)s+=8}if(Number.isFinite(a.volatility)){if(a.volatility>45)s-=25;else if(a.volatility>30)s-=12;else if(a.volatility<18)s+=8}if(Number.isFinite(a.debtToEquity)){if(a.debtToEquity>2)s-=25;else if(a.debtToEquity>1)s-=12;else if(a.debtToEquity<.5)s+=8}return clamp(s)}
  function qualityScore(a){return avg([norm(a.roe,0,35),norm(a.roic,0,30),norm(a.operatingMargin,0,35),norm(a.fcfMargin,0,30),norm(a.earningsStability,-30,30),norm(a.revenueQuality,0,100)])}
  function valuationScore(a){return avg([norm(a.marginOfSafety,-30,50),Number.isFinite(a.pe)?clamp(100-(a.pe-8)*2.2):null,Number.isFinite(a.evEbitda)?clamp(100-(a.evEbitda-6)*4):null])}
  function growthScore(a){return avg([norm(a.revenueGrowth,-20,40),norm(a.epsGrowth,-30,50),norm(a.fcfGrowth,-30,50)])}
  function financialScore(a){return avg([norm(a.debtToEbitda,4,0),norm(a.currentRatio,.5,3),norm(a.interestCoverage,0,20),norm(a.fcfMargin,-10,30)])}
  function trendScore(a){return avg([norm(a.return1m,-20,20),norm(a.return6m,-40,60),norm(a.return12m,-50,100)])}
  function drawdownScore(a){return Number.isFinite(a.drawdown)?clamp(50+Number(a.drawdown)*1.5):null}
  function diversificationScore(a,ctx){let s=70;const w=ctx.assetWeights?.[a.ticker]||0,sw=ctx.sectorWeights?.[a.sector]||0,cw=ctx.countryWeights?.[a.country]||0;if(w>DEFAULT.maxPosition)s-=35;else if(w>.07)s-=15;else if(w<.02)s+=10;if(sw>DEFAULT.maxSector)s-=25;else if(sw>.20)s-=10;else if(sw<.08)s+=8;if(cw>DEFAULT.maxCountry)s-=20;else if(cw>.35)s-=8;else if(cw<.15)s+=5;if(a.assetType==='ETF')s+=3;return clamp(s)}
  function score(asset,ctx={}){const values={quality:qualityScore(asset),valuation:valuationScore(asset),growth:growthScore(asset),financialStrength:financialScore(asset),trend:trendScore(asset),drawdown:drawdownScore(asset),diversification:diversificationScore(asset,ctx),liquidity:norm(asset.avgVolume,0,5000000),risk:riskScore(asset)};let total=0,weight=0,missing=0;Object.entries(DEFAULT.weights).forEach(([k,w])=>{const v=values[k];if(v===null){missing++;return}total+=v*w;weight+=w});const raw=weight?total/weight:0;const concentrationPenalty=(ctx.assetWeights?.[asset.ticker]||0)>DEFAULT.maxPosition?25:0;const sectorPenalty=(ctx.sectorWeights?.[asset.sector]||0)>DEFAULT.maxSector?12:0;const stalePenalty=asset.updatedAt&&Date.now()-new Date(asset.updatedAt).getTime()>7*86400000?20:0;const missingPenalty=missing>=DEFAULT.maxMissingCritical?30:missing*10;const final=clamp(raw-concentrationPenalty-sectorPenalty-stalePenalty-missingPenalty);let confidence=clamp(100-missing*18-stalePenalty);if(!asset.price||!asset.currency)confidence=Math.min(confidence,45);const action=confidence<55?'DATOS_INSUFICIENTES':final>=DEFAULT.thresholds.opportunity?'OPORTUNIDAD':final>=DEFAULT.thresholds.watch?'VIGILAR':'ESPERAR';return{version:VERSION,score:Math.round(final),confidence:Math.round(confidence),action,components:values,missing,penalties:{concentration:concentrationPenalty,sector:sectorPenalty,stale:stalePenalty,data:missingPenalty}}}
  function buildContext(positions,patrimony){const t=Math.max(1,Number(patrimony)||0),assetWeights={},sectorWeights={},countryWeights={};(positions||[]).forEach(p=>{const v=Number(p.valueEUR)||0;assetWeights[p.ticker||p.name]=v/t;if(p.sector)sectorWeights[p.sector]=(sectorWeights[p.sector]||0)+v/t;if(p.country)countryWeights[p.country]=(countryWeights[p.country]||0)+v/t});return{assetWeights,sectorWeights,countryWeights}}
  window.RadarEngineV3={VERSION,DEFAULT,score,buildContext,rank(list,ctx){return(list||[]).map(a=>({...a,radar:score(a,ctx)})).sort((a,b)=>b.radar.score-a.radar.score)}};
})();
