/* RADAR UI V3 — interfaz mobile-first */
(function(){
 function boot(){
  if(typeof pages==='undefined'||typeof rows!=='function'||typeof total!=='function'||typeof esc!=='function'){setTimeout(boot,100);return;}
  pages.radar=function(){
   const rs=rows().filter(r=>Number(r.valueEUR)>0), t=Math.max(1,total());
   const ctx=window.RadarEngineV3?RadarEngineV3.buildContext(rs,t):{};
   const ranked=window.RadarEngineV3?RadarEngineV3.rank(rs.map(r=>({ticker:r.name,name:r.name,price:r.quote,valueEUR:r.valueEUR,assetType:'stock',updatedAt:data.market?.lastSync})),ctx):rs.map(r=>({...r,radar:{score:0,confidence:0,action:'DATOS_INSUFICIENTES'}}));
   const opp=ranked.filter(x=>x.radar.action==='OPORTUNIDAD'),watch=ranked.filter(x=>x.radar.action==='VIGILAR');
   const climate=opp.length>=2?'FAVORABLE':watch.length>=2?'SELECTIVO':'PRUDENTE';
   document.getElementById('app').innerHTML=`<div class="radar-head"><div><span class="radar-eyebrow">INTELLIGENCE CENTER</span><h2>🔎 Radar</h2><p>Oportunidades y riesgos para <b>tu cartera</b>.</p></div><div class="climate ${climate==='FAVORABLE'?'good':climate==='SELECTIVO'?'warn':'care'}">${climate}<small>clima</small></div></div><div class="radar-stats"><div><b>${opp.length}</b><span>Oportunidades</span></div><div><b>${watch.length}</b><span>En vigilancia</span></div><div><b>${ranked.length}</b><span>Analizados</span></div></div><div class="radar-card hero-radar"><div><span class="radar-eyebrow">PRÓXIMO EURO</span><h3>${ranked[0]?esc(ranked[0].name):'Sin señal'}</h3><p>${ranked[0]?labelText(ranked[0].radar.action):'Necesitamos más datos.'}</p></div><strong>${ranked[0]?ranked[0].radar.score:'—'}<small>/100</small></strong></div><div class="radar-card"><div class="radar-title"><h3>🏆 Mejores oportunidades</h3><span>Por encaje</span></div>${ranked.slice(0,8).map(card).join('')}</div><div class="radar-card"><div class="radar-title"><h3>🛡️ Control de riesgo</h3><span>Antes de invertir</span></div><div class="risk-line"><span>Concentración máxima</span><b>${rs.length?Math.round(Math.max(...rs.map(r=>r.valueEUR/t))*100):0}%</b></div><div class="risk-line"><span>Liquidez disponible</span><b>${typeof money==='function'?money(typeof liq==='function'?liq():0):'—'}</b></div><p class="hint">El Radar penaliza oportunidades que empeoran demasiado la concentración.</p></div><div class="radar-card"><div class="radar-title"><h3>🌡️ Factores</h3><span>Vista rápida</span></div><div class="chips"><i>Fundamentales</i><i>Valoración</i><i>Macro</i><i>Noticias</i><i>Riesgo</i><i>Diversificación</i></div><p class="hint">Macro y noticias complementan los fundamentales; no los sustituyen.</p></div><div class="radar-card"><h3>🔬 Regla de seguridad</h3><p class="safety">Si faltan datos críticos o la confianza es insuficiente, <b>no se fuerza una recomendación</b>.</p></div>`;
  };
  function labelText(a){return a==='OPORTUNIDAD'?'Mejor equilibrio actual entre oportunidad y encaje con la cartera.':a==='VIGILAR'?'Interesante, pero todavía necesita confirmación.':'No hay evidencia suficiente para concentrar capital.'}
  function card(x,i){const r=x.radar||{},cls=r.action==='OPORTUNIDAD'?'good':r.action==='VIGILAR'?'warn':'care';return `<div class="radar-item"><div class="rank">${i+1}</div><div class="radar-main"><b>${esc(x.name)}</b><span>${r.action||'ESPERAR'} · confianza ${r.confidence||0}%</span></div><div class="radar-score ${cls}">${r.score||0}</div></div>`}
  const s=document.createElement('style');s.textContent=`.radar-head{display:flex;justify-content:space-between;align-items:center;margin:4px 2px 14px}.radar-head h2{margin:3px 0;font-size:28px}.radar-head p{margin:0;color:var(--muted);font-size:13px}.radar-eyebrow{font-size:10px;font-weight:800;letter-spacing:1.5px;color:var(--blue)}.climate{min-width:78px;text-align:center;border-radius:14px;padding:10px 8px;font-weight:800;font-size:11px}.climate small{display:block;font-weight:500;margin-top:3px}.climate.good,.radar-score.good{background:#e9f8ef;color:#167347}.climate.warn,.radar-score.warn{background:#fff7df;color:#8a5a00}.climate.care,.radar-score.care{background:#fdecec;color:#b52c2c}.radar-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:10px}.radar-stats div{background:#fff;border:1px solid var(--border);border-radius:13px;padding:12px}.radar-stats b{font-size:23px;display:block}.radar-stats span{font-size:11px;color:var(--muted)}.radar-card{background:#fff;border:1px solid var(--border);border-radius:17px;padding:15px;margin:10px 0;box-shadow:0 2px 8px #00000008}.hero-radar{background:linear-gradient(135deg,#111827,#253b66);color:#fff;display:flex;justify-content:space-between;align-items:center}.hero-radar .radar-eyebrow{color:#a8c7ff}.hero-radar h3{font-size:21px;margin:5px 0}.hero-radar p{margin:0;color:#cbd5e1;font-size:12px}.hero-radar>strong{font-size:38px}.hero-radar strong small{font-size:11px;color:#cbd5e1}.radar-title{display:flex;justify-content:space-between;align-items:center}.radar-title h3{margin:0 0 8px}.radar-title span{font-size:11px;color:var(--muted)}.radar-item{display:flex;align-items:center;gap:10px;padding:12px 0;border-bottom:1px solid var(--border)}.radar-item:last-child{border-bottom:0}.rank{width:25px;height:25px;border-radius:50%;background:#eef2f7;display:grid;place-items:center;font-size:11px;font-weight:800}.radar-main{flex:1}.radar-main b{display:block;font-size:14px}.radar-main span{display:block;color:var(--muted);font-size:10px;margin-top:3px}.radar-score{width:42px;height:42px;border-radius:11px;display:grid;place-items:center;font-weight:900}.risk-line{display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid var(--border);font-size:13px}.hint{font-size:11px;color:var(--muted);line-height:1.5}.chips{display:flex;flex-wrap:wrap;gap:6px}.chips i{font-style:normal;background:#eef2f7;border-radius:99px;padding:6px 9px;font-size:11px}.safety{background:#fff7df;padding:11px;border-radius:10px;font-size:12px;line-height:1.5}`;document.head.appendChild(s);
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
